### ISSUE TITLE
Don't hide Microsoft signed entries in AutorunsToWinEventLog

### ISSUE THREAD

**Issue by Centurion89** [palantir/windows-event-forwarding#11]
https://github.com/palantir/windows-event-forwarding/blob/master/AutorunsToWinEventLog/AutorunsToWinEventLog.ps1#L20

Specifically slide 14 and 15: https://github.com/huntresslabs/evading-autoruns/blob/master/Evading_Autoruns_Slides.pdf

**Comment by cryps1s** [comment]
Handled via branch: https://github.com/palantir/windows-event-forwarding/pull/13
