### ISSUE TITLE
character encoding problems with some files

### ISSUE THREAD

**Issue by patrickg2525** [palantir/windows-event-forwarding#24]
I'm noticing some character encoding (or otherwise corrupted) issues with the Account-Management.xml file. 
For example... `<Select Path="Security">*[System[(EventID &gt;=4780 and EventID &lt;=4782)]]</Select>`
Should be ...  `<Select Path="Security">*[System[(EventID >=4780 and EventID <=4782)]]</Select>`

I've just started looking into this repository, so not sure if it occurs elsewhere. 

This has been a great help getting started with WEF though - thanks!

**Comment by clong** [comment]
Hey @patrickg2525 - it may long wrong, but this formatting is actually completely supported by XPath. Sorry if it makes it a bit harder to read, but it should work just fine.

**Comment by patrickg2525** [comment]
thanks for the reply - yes, everything is working fine!
